# Non-sensitive variables
mysql_database: juiceshop
waf_container_name: waf
loki_url: http://loki:3100

# Sensitive variables (mysql especially)
mysql_root_password: "{{ vault_mysql_root_password }}"
app_password: "{{ vault_app_password }}" # Password for application user
# If not defined, a default password will be used

# Application variables for hardening
app_user: "oracle_user"          # User who will use the database
app_database: "{{ mysql_database }}" # Uses existing variable
