{
 "title": "Security Overview",
 "tags": [
  "security",
  "waf",
  "devsecops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Volume de logs WAF",
   "type": "timeseries",
   "description": "Volume total de requêtes passant par le WAF dans le temps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"waf\"} [$__interval])",
     "legendFormat": "Tous les logs"
    }
   ]
  },
  {
   "title": "Requêtes bloquées (403)",
   "type": "timeseries",
   "description": "Requêtes bloquées par le WAF (HTTP 403)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"waf\"} |= \"403\" [$__interval])",
     "legendFormat": "403 bloqués"
    }
   ]
  },
  {
   "title": "Top URIs attaquées",
   "type": "barchart",
   "description": "Top 10 des URL les plus ciblées par des attaques bloquées",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (count_over_time({job=\"waf\"} |= \"403\" | json | __error__=\"\" [$__interval])))",
     "legendFormat": "{{ uri }}"
    }
   ]
  }
 ]
}