{
 "title": "Security Overview",
 "tags": [
  "security",
  "waf",
  "devsecops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "WAF Log Volume",
   "type": "timeseries",
   "description": "Total volume of requests passing through the WAF over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"waf\"} [$__interval])",
     "legendFormat": "All logs"
    }
   ]
  },
  {
   "title": "Blocked Requests (403)",
   "type": "timeseries",
   "description": "Requests blocked by the WAF (HTTP 403)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"waf\"} |= \"403\" [$__interval])",
     "legendFormat": "Blocked 403 requests"
    }
   ]
  },
  {
   "title": "Top attacked",
   "type": "barchart",
   "description": "Top 10 of the most attacks URI and blocked attacks",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (count_over_time({job=\"waf\"} |= \"403\" | json | __error__=\"\" [$__interval])))",
     "legendFormat": "{{ uri }}"
    }
   ]
  }
 ]
}