# Playbook de bootstrap (préparation des hôtes)
---
- name: Installer Python sur les conteneurs pour permettre l'exécution d'Ansible
  hosts: all
  gather_facts: no # Ansible ne récolte rien (IMPORTANT!)
  tasks:
    - name: Installer Python3 sur les conteneurs basés sur Debian (WAF)
      raw: apt-get update && apt-get install -y python3
      when: inventory_hostname in groups['waf_servers'] # Waf only
      changed_when: false # Pollution maîtrisée
      

    - name: Installer Python3 sur les conteneurs basés sur Oracle Linux (MySQL)
      raw: microdnf install -y python3
      when: inventory_hostname in groups['db_servers']
      changed_when: false
