# Fichier d'inventaire pour Ansible

[waf_servers]
waf ansible_connection=community.docker.docker

[db_servers]
mysql-db ansible_connection=community.docker.docker

[monitoring_servers]
waf ansible_connection=community.docker.docker

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=root