# Fichier d'inventaire pour Ansible

[waf]
waf ansible_connection=community.docker.docker

[database]
mysql-db ansible_connection=community.docker.docker

[monitoring]
waf ansible_connection=community.docker.docker

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=root